### ISSUE TITLE
Make the HAS skeleton - initial version HAS0.1

### ISSUE THREAD

**Issue by amichai-bd** [ChrisShakkour/RV32I-MAF-project#10]
You may write the HAS in "MarkDown"(in the Wiki section of this git repository) or a "Word" file.
Please see the reference I send you as a starting point.

**Comment by amichai-bd** [comment]
This can be marked as Done? @ChrisShakkour

**Comment by ChrisShakkour** [comment]
@amichai-bd yes done!
