### ISSUE TITLE
Understand the crt0 file - design a simple crt0 for your tests

### ISSUE THREAD

**Issue by amichai-bd** [ChrisShakkour/RV32I-MAF-project#12]
See here:
https://en.wikipedia.org/wiki/Crt0#:~:text=crt0%20(also%20known%20as%20c0,calling%20the%20program's%20main%20function.
You may want to always use the crt0 to initial the register file, set the stack pointer etc.

**Comment by ChrisShakkour** [comment]
crt0.S created under scripts/crt0/crt0.S

first adresses 0x00-0x20 are reserved for jal to handlers.
