### ISSUE TITLE
understanding the "-nostartfiles" flag

### ISSUE THREAD

**Issue by amichai-bd** [ChrisShakkour/RV32I-MAF-project#13]
See here linker options:
https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html

## Please try this on your GCC and code.

Example of code generated with the "-nostartfiles" flag:
> riscv32-unknown-elf-gcc  -O3  -march=rv32i -nostartfiles  Multi_Core.c.s -o Multi_Core.elf  

As you can see - the "linker" did not add any init, _start, etc.
Machine code starts from "main" (the 00010054 offset is the default value - you may want to override it with your own linker)
![image](https://user-images.githubusercontent.com/81047407/138747901-4a2a8cf7-85d8-4c19-9598-92fc01f59203.png)

Once i remove the  "-nostartfiles" flag:
> riscv32-unknown-elf-gcc  -O3  -march=rv32i Multi_Core.c.s -o Multi_Core.elf  

the Linker will add whatever it wants (which you may want or not.)
- register_fini
- start
- __do_global_dtors_aux
- frame_dummy
- exit
- __libc_init_array
- memset
- __call_exitprocs,atexit
![image](https://user-images.githubusercontent.com/81047407/138748153-d229dcdf-dd94-46dd-a21a-d679281e2f2b.png)

**Comment by ChrisShakkour** [comment]
resolved, the linker script was corrupted, fixed!
