### ISSUE TITLE
psuedo code and register ABI naming removed (couldn't tag you, so i made an issue)

### ISSUE THREAD

**Issue by ChrisShakkour** [ChrisShakkour/RV32I-MAF-project#33]
https://github.com/ChrisShakkour/RV32I-MAF-project/blob/c6c0692d8e52069e7432bd6149c8ce4a2b5d676a/verif/tests/TowerOfHanoi/TowerOfHanoi.txt.mono#L18

add the following to objdump command:
-Mno-aliases -> to remove pseudo code (j to be seen as jal) 
-M numeric   -> to remove ABI register names (sp to be seen as x2)

enjoy!

**Comment by amichai-bd** [comment]
This looks great!! thanks for for showing me.

**Comment by amichai-bd** [comment]
This looks great!! thanks for for showing me.
